### ISSUE TITLE
Failed to load the giphy package

### ISSUE THREAD

**Issue by smashwilson** [rgbkrk/atom-giphy#2]
[Enter steps to reproduce below:]
1. This happened on launch with giphy installed on the latest Atom. (0.206.0 has deprecated methods disabled by default in preparation for 1.0)

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [giphy](https://github.com/rgbkrk/atom-giphy) package, v0.1.0
### Stack Trace

Failed to load the giphy package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/ashl6947/.atom/packages/giphy/lib/giphy-view.coffee:5:199)
    at /Users/ashl6947/.atom/packages/giphy/lib/giphy-view.coffee:24:5
    at Object.<anonymous> (/Users/ashl6947/.atom/packages/giphy/lib/giphy-view.coffee:142:5)
    at Object.<anonymous> (/Users/ashl6947/.atom/packages/giphy/lib/giphy-view.coffee:144:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      "*.o",
      ".git",
      ".DS_Store",
      "*.out",
      "*.pyc"
    ],
    "disabledPackages": [
      "atom-color-highlight",
      "atom-randomstring",
      "linter-pep8"
    ],
    "projectHome": "/Users/ashl6947/code",
    "themes": [
      "astromac-ui",
      "atom-light-syntax"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
astromac-ui, v0.1.0
atom-pair, v1.1.6
atom-spotify2, v2.1.1
atomatigit, v1.5.3
autocomplete-emojis, v2.2.2
autocomplete-paths, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
character-table, v0.2.0
color-picker, v2.0.4
filesize, v0.2.0
fonts, v0.4.2
giphy, v0.1.0
git-log, v0.4.1
go-plus, v3.3.11
hex, v0.6.2
language-docker, v1.1.3
language-ember-htmlbars, v0.3.0
language-gitignore, v0.2.0
language-restructuredtext, v0.6.0
language-rust, v0.4.3
language-systemd, v0.1.0
line-diff-details, v1.1.1
linter, v0.12.6
linter-flake8, v1.4.2
linter-jshint, v0.1.6
minimap, v4.9.4
minimap-selection, v4.2.0
pretty-json, v0.3.3
racer, v0.11.0
regex-railroad-diagram, v0.7.4
script, v2.23.0
symbols-tree-view, v0.9.3

# Dev
giphy, v0.0.3
go-plus, v2.0.8
```

**Comment by rgbkrk** [comment]
Haha, oh you Ash.

**Comment by mgarciaisaia** [comment]
The package is broken, but I can't understand why the stacktrace reports lines that don't match the problem (ie, `giphy-view.coffee:5` has a comment).
